### ISSUE TITLE
Problem in supernet ddp training

### ISSUE THREAD

**Issue by XuanmaiXue** [liangyn22/MCUFormer#2]
I use this command to start the training of supernet 
```
CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 --use_env supernet_train.
py --data-path /data0/xmx/imagenet --gp --change_qk --relative_position --mode super --dist-eval --load-pretrained-model --cfg ./experiments/sup
ernet/supernet-T.yaml --cfg-new  ./experiments/supernet/supernet-T-new.yaml --epochs 500 --warmup-epochs 5 --lr 1e-4 --super_epoch 1 --step-num 
7 --model deit_tiny_patch16_224 --batch-size 128 --output ./supernet
```

but this error occurs

`RuntimeError: [2]: params[4] in this process with sizes [243, 256] appears not to match sizes of the same param in process 0.
number of params: 16818120`

**Comment by liangyn22** [comment]
could you please provide more details of your enviroment and error?

**Comment by XuanmaiXue** [comment]
> could you please provide more details of your enviroment and error?

This is my python environment  Python = 3.10.13, use RTX3090
```
Package                  Version
------------------------ ----------
certifi                  2023.11.17
charset-normalizer       3.3.2
easydict                 1.11
filelock                 3.13.1
fsspec                   2023.10.0
huggingface-hub          0.19.4
idna                     3.4
imageio                  2.33.0
Jinja2                   3.1.2
lazy_loader              0.3
MarkupSafe               2.1.3
mpmath                   1.3.0
networkx                 3.2.1
numpy                    1.26.2
nvidia-cublas-cu12       12.1.3.1
nvidia-cuda-cupti-cu12   12.1.105
nvidia-cuda-nvrtc-cu12   12.1.105
nvidia-cuda-runtime-cu12 12.1.105
nvidia-cudnn-cu12        8.9.2.26
nvidia-cufft-cu12        11.0.2.54
nvidia-curand-cu12       10.3.2.106
nvidia-cusolver-cu12     11.4.5.107
nvidia-cusparse-cu12     12.1.0.106
nvidia-nccl-cu12         2.18.1
nvidia-nvjitlink-cu12    12.3.101
nvidia-nvtx-cu12         12.1.105
opencv-python            4.8.1.78
packaging                23.2
Pillow                   10.1.0
pip                      23.3.1
ptflops                  0.7.1.2
PyYAML                   6.0.1
requests                 2.31.0
safetensors              0.4.0
scikit-image             0.22.0
scipy                    1.11.4
setuptools               68.0.0
sympy                    1.12
tifffile                 2023.9.26
timm                     0.9.11
torch                    2.1.1
torchvision              0.16.1
tqdm                     4.66.1
triton                   2.1.0
typing_extensions        4.8.0
urllib3                  2.1.0
wheel                    0.41.2
```
more details about error
```
[[0.9, 16, 0.597, 0.324], [0.6, 16, 0.17549056363105775, 0.67], [0.85, 20, 0.502377359919548, 1.0], [0.95, 28, 0.27894339266061785, 1.0], [0.65, 28, 0.611, 1.0]]
error [-0.20658185 -0.0031707 ]
sram [ 0.3146697  -0.03929784]
error [-0.20658185 -0.0031707 ]
sram [ 0.3146697  -0.03929784]
error [-0.20658185 -0.0031707 ]
sram [ 0.3146697  -0.03929784]
error [-0.20658185 -0.0031707 ]
sram [ 0.3146697  -0.03929784]
error [-0.20658185 -0.0031707 ]
sram [ 0.3146697  -0.03929784]
Creating SuperVisionTransformer that rank ratio is 0.9 and patch size is 16
Traceback (most recent call last):
  File "/home/xmx70/MCUFormer/supernet_train.py", line 940, in <module>
    main(args)
  File "/home/xmx70/MCUFormer/supernet_train.py", line 340, in main
    model = torch.nn.parallel.DistributedDataParallel(model, device_ids=[args.gpu], find_unused_parameters=True)
  File "/home/xmx70/miniconda3/envs/mcuformer/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 795, in __init__
    _verify_param_shape_across_processes(self.process_group, parameters)
  File "/home/xmx70/miniconda3/envs/mcuformer/lib/python3.10/site-packages/torch/distributed/utils.py", line 265, in _verify_param_shape_across_processes
    return dist._verify_params_across_processes(process_group, tensors, logger)
RuntimeError: [2]: params[4] in this process with sizes [243, 256] appears not to match sizes of the same param in process 0.
number of params: 16818120
[2023-11-24 14:02:30,178] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 1217403 closing signal SIGTERM
[2023-11-24 14:02:30,179] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 1217404 closing signal SIGTERM
[2023-11-24 14:02:30,179] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 1217406 closing signal SIGTERM
[2023-11-24 14:02:32,865] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 2 (pid: 1217405) of binary: /home/xmx70/miniconda3/envs/mcuformer/bin/python
Traceback (most recent call last):
  File "/home/xmx70/miniconda3/envs/mcuformer/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/xmx70/miniconda3/envs/mcuformer/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/xmx70/miniconda3/envs/mcuformer/lib/python3.10/site-packages/torch/distributed/launch.py", line 196, in <module>
    main()
  File "/home/xmx70/miniconda3/envs/mcuformer/lib/python3.10/site-packages/torch/distributed/launch.py", line 192, in main
    launch(args)
  File "/home/xmx70/miniconda3/envs/mcuformer/lib/python3.10/site-packages/torch/distributed/launch.py", line 177, in launch
    run(args)
  File "/home/xmx70/miniconda3/envs/mcuformer/lib/python3.10/site-packages/torch/distributed/run.py", line 797, in run
    elastic_launch(
  File "/home/xmx70/miniconda3/envs/mcuformer/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/xmx70/miniconda3/envs/mcuformer/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
supernet_train.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-11-24_14:02:30
  host      : 1070
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 1217405)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
```
